spring:
  datasource:
    url: jdbc:mysql://192.168.98.133:3306/student?useUnicode=true&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

mybatis:
  type-aliases-package: com.zzus.springbook.entity
  mapper-locations: classpath:mapper/*.xml

token:
  header: Token
  secret: secret
  expiration: 604800