spring:
  resources:
    static-locations: classpath:webapp/
  datasource:
    url: jdbc:mysql://{host}:3306/book-system?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.jdbc.Driver
    username: {username}
    password: {password}
  redis:
    host: {host}
    port: {port}
    password: {username}
    database: 0

    pool:
      max-active: 32
      max-wait: 300
      max-idle: 16
      min-idle: 8

mybatis:
  type-aliases-package: com.zzus.springbook.entity
  mapper-locations: classpath:mapper/*.xml

token:
  header: Token
  secret: secret
  expiration: 604800

